### ISSUE TITLE
[Bug] '/pa install' throws out an error.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#115]
```
[15:58:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.0.556
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.commands.PAA_Install.listVersions(PAA_Install.java:113) ~[?:?]
	at net.slipcor.pvparena.commands.PAA_Install.commit(PAA_Install.java:64) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:260) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-PaperSpigot-5063a06-d3e0b6f]
	... 15 more
```

**Comment by mibby** [comment]
```/pa install``` no longer errors when typing, but still errors when trying to install a mod or entering a random name. 

```
[18:17:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.1.43
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.commands.PAA_Install.commit(PAA_Install.java:73) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:260) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-PaperSpigot-a55011e-d3e0b6f]
	... 15 more
```

Seeing how the install command is pointless if the update check is disabled and the install.yml is blank, you can safely ignore this ticket/error. :)
