### ISSUE TITLE
[Bug] Update check misconfigured.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#144]
Still had the setting enabled on my test server and noticed this getting outputted on the check.
```
[18:09:03] [Server thread/INFO]: [PVP Arena] Plugin tracking enabled. Set 'tracker: false' inside the main config to disable.
[18:09:03] [Thread-8/INFO]: Checking for updates...
[18:09:03] [Server thread/INFO]: [PVP Arena] enabled (version pvparena v1.3.2.58)
[18:09:03] [Thread-8/WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.spigotmc.org/api/general.php
[18:09:03] [Thread-8/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[18:09:03] [Thread-8/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[18:09:03] [Thread-8/WARN]: 	at net.slipcor.pvparena.core.Updater.runTest(Updater.java:429)
[18:09:03] [Thread-8/WARN]: 	at net.slipcor.pvparena.core.Updater.run(Updater.java:329)
```

**Comment by slipcor** [comment]
hm I saw this once and hoped it was my fault....... well then, I have to change my update check :(

**Comment by slipcor** [comment]
v1.3.2.59 - fix update check

**Comment by mibby** [comment]
Confirmed fixed.

```
[19:09:36] [Server thread/INFO]: [PVP Arena] Plugin tracking enabled. Set 'tracker: false' inside the main config to disable.
[19:09:36] [Thread-8/INFO]: Checking for updates...
[19:09:36] [Server thread/INFO]: [PVP Arena] enabled (version pvparena v1.3.2.59)
```
