### ISSUE TITLE
PVPArena 1.9 inventory rollback error.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#160]
Ticket until fixed upstream.

```
[16:25:20] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.2.83
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventory.setContents(CraftInventory.java:65) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.slipcor.pvparena.arena.ArenaPlayer.reloadInventory(ArenaPlayer.java:333) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1294) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.removePlayer(Arena.java:1049) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.playerLeave(Arena.java:864) ~[?:?]
	at net.slipcor.pvparena.commands.PAG_Leave.commit(PAG_Leave.java:54) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:378) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	... 15 more
```

**Comment by mibby** [comment]
Fixed upstream.
