### ISSUE TITLE
error when /pa info : ClassCastException String cannot be cast to Integer

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#161]
```[20:21:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.2.75
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
at net.slipcor.pvparena.core.Config.getInt(Config.java:612) ~[?:?]
at net.slipcor.pvparena.commands.PAI_Info.commit(PAI_Info.java:196) ~[?:?]
at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:378) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
... 15 more```

**Comment by Oruss7** [comment]
I have `autoClass` set to  `player` class

**Comment by slipcor** [comment]
wow, it is not the ready class, it is the ready BLOCK - give me a minute, keep your eyes on the jenkins :)

**Comment by Oruss7** [comment]
Oww i like it! you're so fast

**Comment by slipcor** [comment]
Yeah I got lucky, I just saw the thingie and was coding anyways :D let's leave this open, I need to fix the ready block definition, but not before 1.9 is stable

**Comment by Oruss7** [comment]
okay, thanks. But i 'm not running 1.9,  it's spigot 1.8.8

**Comment by slipcor** [comment]
oh yeah sure. but I mean, I am planning a rewrite IN 1.9 that will fix a lot of things and maybe get some people to update their stuffs, still quite some people on 1.7 -.-

**Comment by Oruss7** [comment]
Ah okay. Can you add jenkins link to the readme plz?

**Comment by slipcor** [comment]
oh I thought I did. here it is:
https://ci2.craftyn.com/job/PVP%20Arena/

I'll add it to the readme but not push now

**Comment by Oruss7** [comment]
thanks, have a good night !

**Comment by Oruss7** [comment]
is the fix available in 1.8.8 ?  the 1.9 is retro-compatible with the 1.8 ?

**Comment by slipcor** [comment]
I am quite sure that everything I pushed (in your case v1.3.2.84) is compatible with 1.8 :)

https://ci2.craftyn.com/job/PVP%20Arena/

If not I will make a build for bukkit 1.8 on DBO, need your feedback though :)

**Comment by slipcor** [comment]
hi?

**Comment by Oruss7** [comment]
Done, sorry i forgot to close.
