### ISSUE TITLE
Error with worldedit module

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#163]
My region is `tnt_run_battle` and the file is `tnt_run_battle`

```
[18:34:45] [Server thread/INFO]: Oruss7 issued server command: /pa regsave tnt_run_battle tnt_run_battle
[18:34:59] [Server thread/INFO]: Oruss7 issued server command: /pa regload tnt_run_battle
[18:34:59] [Server thread/WARN]: java.io.FileNotFoundException: plugins/pvparena/tnt_run_tnt_run_battle.schematic (No such file or directory)
[18:34:59] [Server thread/WARN]: at java.io.FileInputStream.open0(Native Method)
[18:34:59] [Server thread/WARN]: at java.io.FileInputStream.open(FileInputStream.java:195)
[18:34:59] [Server thread/WARN]: at java.io.FileInputStream.(FileInputStream.java:138)
[18:34:59] [Server thread/WARN]: at com.sk89q.worldedit.schematic.MCEditSchematicFormat.load(MCEditSchematicFormat.java:200)
[18:34:59] [Server thread/WARN]: at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:188)
[18:34:59] [Server thread/WARN]: at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:182)
[18:34:59] [Server thread/WARN]: at net.slipcor.pvparena.modules.worldedit.PAWE.commitCommand(PAWE.java:96)
[18:34:59] [Server thread/WARN]: at net.slipcor.pvparena.classes.PACheck.handleCommand(PACheck.java:141)
[18:34:59] [Server thread/WARN]: at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:359)
[18:34:59] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:34:59] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:34:59] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:34:59] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:34:59] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:34:59] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:34:59] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
```

**Comment by slipcor** [comment]
quote "plugins/pvparena/tnt_run_tnt_run_battle.schematic (No such file or directory)"

does the file exist?

why didnt you save and load with the same logic? if you save with a name you should also load with the same name :)

**Comment by slipcor** [comment]
/pa regsave tnt_run_battle tnt_run_battle

should lead to

/pa regload tnt_run_battle tnt_run_battle

**Comment by Oruss7** [comment]
Right. That's working. 
`/pa !we create` what is that ? I test this command and now i need to select 2 points but not select not working...

**Comment by Oruss7** [comment]
My file is named `tnt_run_battle.shcematic` and NOT `tnt_run_tnt_run_battle.schematic`

**Comment by slipcor** [comment]
exactly, because you used the command "/pa regsave tnt_run_battle tnt_run_battle"

by that command you forced the name to "tnt_run_battle.schematic"

**Comment by Oruss7** [comment]
so that's explain with commands, i can regen but not automatically. The module add the arena name before the arena region ? like `'<arena_name>_<arena_region>.schematic'`

**Comment by slipcor** [comment]
oh. yeah. To save correctly to be read this way, please use the regsave command without arena name override:

/pa regsave tnt_run_battle

this will save the arena region in a way that PA reads it automatically with autoload ;)

**Comment by Oruss7** [comment]
AHHH okay. Sorry, misunderstanding. I will had this info to the doc (with /region remove command ^^)
