### ISSUE TITLE
[Bug]  StructureGrowEvent

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#168]
``` 
[18:19:49] [Server thread/ERROR]: Could not pass event StructureGrowEvent to pvparena v1.3.2.86
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.BlockSapling.b(BlockSapling.java:51) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.Block.a(Block.java:299) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.WorldServer.h(WorldServer.java:495) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:253) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
at net.slipcor.pvparena.loadables.ArenaModuleManager.onBlockChange(ArenaModuleManager.java:147) ~[?:?]
at net.slipcor.pvparena.listeners.BlockListener.onBlockGrow(BlockListener.java:325) ~[?:?]
at sun.reflect.GeneratedMethodAccessor746.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
... 12 more
```

v1.3.2.86
walls : v1.3.2.51

**Comment by Oruss7** [comment]
and the same game, i had this (on game start) :  

```
[18:08:48] [Server thread/WARN]: [PVP Arena] Task #198845 for pvparena v1.3.2.86 generated an exception
java.lang.NullPointerException
at net.slipcor.pvparena.modules.blockrestore.Blocks.saveChests(Blocks.java:326) ~[?:?]
at net.slipcor.pvparena.modules.blockrestore.Blocks.saveRegion(Blocks.java:361) ~[?:?]
at net.slipcor.pvparena.modules.blockrestore.Blocks.parseStart(Blocks.java:344) ~[?:?]
at net.slipcor.pvparena.classes.PACheck.handleStart(PACheck.java:764) ~[?:?]
at net.slipcor.pvparena.arena.Arena.start(Arena.java:1563) ~[?:?]
at net.slipcor.pvparena.arena.Arena.start(Arena.java:1523) ~[?:?]
at net.slipcor.pvparena.runnables.StartRunnable.commit(StartRunnable.java:41) ~[?:?]
at net.slipcor.pvparena.runnables.ArenaRunnable.run(ArenaRunnable.java:135) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Comment by slipcor** [comment]
You need the latest BlockRestore version to fix both issues :)
