### ISSUE TITLE
Module skin: optional Dependency not optional ...

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#170]
```
[00:45:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: me/libraryaddict/disguise/disguisetypes/Disguise
[00:45:20] [Server thread/WARN]: at java.lang.Class.forName0(Native Method)
[00:45:20] [Server thread/WARN]: at java.lang.Class.forName(Class.java:348)
[00:45:20] [Server thread/WARN]: at net.slipcor.pvparena.ncloader.NCBLoader.load(NCBLoader.java:120)
[00:45:20] [Server thread/WARN]: at net.slipcor.pvparena.ncloader.NCBLoader.reload(NCBLoader.java:212)
[00:45:20] [Server thread/WARN]: at net.slipcor.pvparena.loadables.ArenaModuleManager.reload(ArenaModuleManager.java:290)
[00:45:20] [Server thread/WARN]: at net.slipcor.pvparena.commands.PAA_Install.commit(PAA_Install.java:94)
[00:45:20] [Server thread/WARN]: at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:262)
[00:45:20] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:45:20] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:45:20] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:45:20] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:45:20] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[00:45:20] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[00:45:20] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[00:45:20] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.disguisetypes.Disguise
[00:45:20] [Server thread/WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[00:45:20] [Server thread/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:45:20] [Server thread/WARN]: at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
[00:45:20] [Server thread/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:45:20] [Server thread/WARN]: ... 23 more
[00:45:20] [Server thread/WARN]: [PVP Arena] The JAR file pa_m_skins.jar failed to load
```

**Comment by slipcor** [comment]
please download the latest files from the jenkins, this should be fixed there

**Comment by Oruss7** [comment]
The bug appear justly with the latest files. build 71

**Comment by slipcor** [comment]
Hm please double check that you properly replaced the skins jar in your /files AND /mods folder, I specifically fixed this with the #85 (PA) build :)

https://github.com/slipcor/pvparena_modules/commit/9fa405a934b29dba4541ec13021e1ce8ae890e3c

**Comment by slipcor** [comment]
@Oruss7 try latest jenkins build, I messed up the ZIP file building :/

**Comment by Oruss7** [comment]
oh i forgot this issue :confused: i test after work

**Comment by Oruss7** [comment]
Working.
