### ISSUE TITLE
IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#190]
```
[09:24:30] [Server thread/ERROR]: Error occurred while disabling pvparena v1.3.2.113 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:407) ~[patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126) ~[patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109) ~[patched_1.9.4.jar:git-Paper-740]
	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.remove(ScoreBoards.java:256) ~[?:?]
	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.resetPlayer(ScoreBoards.java:302) ~[?:?]
	at net.slipcor.pvparena.loadables.ArenaModuleManager.resetPlayer(ArenaModuleManager.java:263) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1285) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1153) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1223) ~[?:?]
	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:343) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:397) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347) [patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.disablePlugins(CraftServer.java:336) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.stop(MinecraftServer.java:463) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:663) [patched_1.9.4.jar:git-Paper-740]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```
```
[00:57:17] [Server thread/INFO]: [PVP Arena] -- PVP Arena version information --
[00:57:17] [Server thread/INFO]: [PVP Arena] PVP Arena version: 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Arena Goals:
[00:57:17] [Server thread/INFO]: [PVP Arena] Beacons - v1.3.2.99
[00:57:17] [Server thread/INFO]: [PVP Arena] BlockDestroy - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Domination - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Flags - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Food - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Infect - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Liberation - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PhysicalFlags - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerDeathMatch - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerKillReward - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerLives - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Sabotage - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Tank - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamDeathConfirm - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamDeathMatch - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamLives - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Time - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Mods:
[00:57:17] [Server thread/INFO]: [PVP Arena] ColorTeams - v1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] BetterFight - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] ScoreBoards - v1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Vault - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] BetterClasses - v1.3.2.94
[00:57:17] [Server thread/INFO]: [PVP Arena] Announcements - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] Skins - v1.3.2.85
[00:57:17] [Server thread/INFO]: [PVP Arena] BlockDissolve - v1.3.2.56
[00:57:17] [Server thread/INFO]: [PVP Arena] WorldEdit - v1.3.2.110
[00:57:17] [Server thread/INFO]: [PVP Arena] Walls - v1.3.2.78
[00:57:17] [Server thread/INFO]: [PVP Arena] RespawnRelay - v1.3.2.60
[00:57:17] [Server thread/INFO]: [PVP Arena] Powerups - v1.3.2.59
[00:57:17] [Server thread/INFO]: [PVP Arena] BattlefieldGuard - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] BattlefieldJoin - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] CustomSpawn - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] RegionTool - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] StandardLounge - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] StandardSpectate - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] WarmupJoin - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Regionshapes:
[00:57:17] [Server thread/INFO]: [PVP Arena] cuboid - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] cylindric - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] spheric - 1.3.2.113
```

**Comment by slipcor** [comment]
I hate bukkit :P v1.3.2.115 - [ColorTeams,Scoreboards] prevent IllegalPluginAccessException

**Comment by mibby** [comment]
Seem to be fine now. :)
