### ISSUE TITLE
Could not pass event PlayerInteractEvent to pvparena

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#191]
```
[15:19:52] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.2.113
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.4.jar:git-Paper-741]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.4.jar:git-Paper-741]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-741]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-741]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-741]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [patched_1.9.4.jar:git-Paper-741]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:111) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:832) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-741]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:818) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-741]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-741]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.goals.GoalLiberation.checkInteract(GoalLiberation.java:199) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handleInteract(PACheck.java:239) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:467) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor236.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-741]
	... 19 more
```
```
[00:57:17] [Server thread/INFO]: [PVP Arena] -- PVP Arena version information --
[00:57:17] [Server thread/INFO]: [PVP Arena] PVP Arena version: 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Arena Goals:
[00:57:17] [Server thread/INFO]: [PVP Arena] Beacons - v1.3.2.99
[00:57:17] [Server thread/INFO]: [PVP Arena] BlockDestroy - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Domination - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Flags - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Food - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Infect - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Liberation - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PhysicalFlags - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerDeathMatch - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerKillReward - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerLives - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Sabotage - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Tank - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamDeathConfirm - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamDeathMatch - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamLives - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Time - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Mods:
[00:57:17] [Server thread/INFO]: [PVP Arena] ColorTeams - v1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] BetterFight - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] ScoreBoards - v1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Vault - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] BetterClasses - v1.3.2.94
[00:57:17] [Server thread/INFO]: [PVP Arena] Announcements - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] Skins - v1.3.2.85
[00:57:17] [Server thread/INFO]: [PVP Arena] BlockDissolve - v1.3.2.56
[00:57:17] [Server thread/INFO]: [PVP Arena] WorldEdit - v1.3.2.110
[00:57:17] [Server thread/INFO]: [PVP Arena] Walls - v1.3.2.78
[00:57:17] [Server thread/INFO]: [PVP Arena] RespawnRelay - v1.3.2.60
[00:57:17] [Server thread/INFO]: [PVP Arena] Powerups - v1.3.2.59
[00:57:17] [Server thread/INFO]: [PVP Arena] BattlefieldGuard - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] BattlefieldJoin - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] CustomSpawn - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] RegionTool - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] StandardLounge - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] StandardSpectate - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] WarmupJoin - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Regionshapes:
[00:57:17] [Server thread/INFO]: [PVP Arena] cuboid - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] cylindric - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] spheric - 1.3.2.113
```

**Comment by mibby** [comment]
In addition, there is no message given when players are liberated and players don't spawn with any items after being liberated.

**Comment by Oruss7** [comment]
that's specific to Liberation goal ?

**Comment by slipcor** [comment]
Yes,  it is an error happening in the Liberation goal.The NPE prevents proper event handling which obviously leads to other issues :) 
Will look into it. Maybe you will see a fix soon. Depends on work.

**Comment by mibby** [comment]
Seems to be working as intended now. Not sure what item was null though, as the class seems to spawn with all items after being liberated.

**Comment by slipcor** [comment]
blame 1.9 :)
