### ISSUE TITLE
NullPointerException: ScoreBoards & ColorTeams

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#192]
```
[22:12:07] [Server thread/WARN]: [PVP Arena] Task #259800 for pvparena v1.3.2.113 generated an exception
java.lang.NullPointerException
	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards$1.run(ScoreBoards.java:262) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:827) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-740]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```
```
[22:12:07] [Server thread/WARN]: [PVP Arena] Task #259801 for pvparena v1.3.2.113 generated an exception
java.lang.NullPointerException
	at net.slipcor.pvparena.modules.colorteams.CTManager$1.run(CTManager.java:190) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:827) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-740]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```
```
[00:57:17] [Server thread/INFO]: [PVP Arena] -- PVP Arena version information --
[00:57:17] [Server thread/INFO]: [PVP Arena] PVP Arena version: 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Arena Goals:
[00:57:17] [Server thread/INFO]: [PVP Arena] Beacons - v1.3.2.99
[00:57:17] [Server thread/INFO]: [PVP Arena] BlockDestroy - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Domination - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Flags - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Food - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Infect - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Liberation - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PhysicalFlags - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerDeathMatch - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerKillReward - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] PlayerLives - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Sabotage - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Tank - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamDeathConfirm - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamDeathMatch - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] TeamLives - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Time - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Mods:
[00:57:17] [Server thread/INFO]: [PVP Arena] ColorTeams - v1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] BetterFight - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] ScoreBoards - v1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] Vault - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] BetterClasses - v1.3.2.94
[00:57:17] [Server thread/INFO]: [PVP Arena] Announcements - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] Skins - v1.3.2.85
[00:57:17] [Server thread/INFO]: [PVP Arena] BlockDissolve - v1.3.2.56
[00:57:17] [Server thread/INFO]: [PVP Arena] WorldEdit - v1.3.2.110
[00:57:17] [Server thread/INFO]: [PVP Arena] Walls - v1.3.2.78
[00:57:17] [Server thread/INFO]: [PVP Arena] RespawnRelay - v1.3.2.60
[00:57:17] [Server thread/INFO]: [PVP Arena] Powerups - v1.3.2.59
[00:57:17] [Server thread/INFO]: [PVP Arena] BattlefieldGuard - v1.3.2.51
[00:57:17] [Server thread/INFO]: [PVP Arena] BattlefieldJoin - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] CustomSpawn - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] RegionTool - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] StandardLounge - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] StandardSpectate - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] WarmupJoin - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] -----------------------------------
[00:57:17] [Server thread/INFO]: [PVP Arena] Regionshapes:
[00:57:17] [Server thread/INFO]: [PVP Arena] cuboid - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] cylindric - 1.3.2.113
[00:57:17] [Server thread/INFO]: [PVP Arena] spheric - 1.3.2.113
```

**Comment by mibby** [comment]
@slipcor Also, is PA spamming task creations / is the task number suppose to get this high? ```Task #3210330``` Noticed the error with task numbers in the millions, on numerous restarts.

**Comment by slipcor** [comment]
I have no idea about tasks :/

v1.3.2.114 - [ColorTeams,Scoreboards] fix NPE when restoring an empty scoreboard

maybe this fixes it?

**Comment by Oruss7** [comment]
Your running the last spigot version ?

**Comment by slipcor** [comment]
mibby always is :) I recon it is the problem. since 1.9, there can occasionally be null items in the inventory :(

**Comment by mibby** [comment]
@slipcor 

```
[11:12:10] [Server thread/WARN]: [PVP Arena] Task #2024220 for pvparena v1.3.2.114 generated an exception
java.lang.NullPointerException
	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards$1.run(ScoreBoards.java:259) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.4.jar:git-Paper-748]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:795) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[11:12:10] [Server thread/WARN]: [PVP Arena] Task #2024219 for pvparena v1.3.2.114 generated an exception
java.lang.NullPointerException
	at net.slipcor.pvparena.modules.colorteams.CTManager$1.run(CTManager.java:192) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.4.jar:git-Paper-748]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:795) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by slipcor** [comment]
boo. who hired this bad developer? I want my money back!

**Comment by slipcor** [comment]
Im an idiot. Look at the code. I should retire mate.

v1.3.2.116 - [ColorTeams,Scoreboards] prevent IllegalPluginAccessException (for real)

**Comment by mibby** [comment]
Everything looks good now.
