### ISSUE TITLE
[CheckPoints] Some players aren't having checkpoints saved

### ISSUE THREAD

**Issue by tmad40blue** [slipcor/pvparena#197]
I've got an arena set up with CheckPoints goal, and EventActions to run "/pa checkpoint" for them upon death. Unfortunately, only some players in the arena are having their checkpoints saved, and when they die, this appears in console:

```
[12:06:22 WARN]: [PVP Arena] Task #288015 for pvparena v1.3.2.117 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.2.117
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at net.slipcor.pvparena.modules.eventactions.EventActions$1RunLater.run(EventActions.java:148) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at net.slipcor.pvparena.goals.GoalCheckPoints.commitCommand(GoalCheckPoints.java:229) ~[pvparena.jar:?]
        at net.slipcor.pvparena.classes.PACheck.handleCommand(PACheck.java:152) ~[pvparena.jar:?]
        at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:361) ~[pvparena.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        ... 11 more
```

**Comment by tmad40blue** [comment]
After a little bit of troubleshooting, I figured out that it's not saving when someone joins AFTER the match begins with "alwaysJoinInBattle" set to "true".

I'm also getting this error spammed in console when someone wins the round - the arena never actually ends itself; I had to do a manual /pa disable:

```
[12:19:30 WARN]: [PVP Arena] Task #390188 for pvparena v1.3.2.117 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between NewPeaceful and TheTrainStation
        at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.Location.distance(Location.java:439) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at net.slipcor.pvparena.goals.GoalCheckPoints.checkLocationPresentPlayers(GoalCheckPoints.java:122) ~[pvparena.jar:?]
        at net.slipcor.pvparena.goals.GoalCheckPoints.checkMove(GoalCheckPoints.java:143) ~[pvparena.jar:?]
        at net.slipcor.pvparena.goals.GoalCheckPoints$CheckPointsMainRunnable.run(GoalCheckPoints.java:413) ~[pvparena.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by slipcor** [comment]
please try the latest version v1.3.2.118 on my jenkins :)

**Comment by tmad40blue** [comment]
Fixed! Checkpoints are being saved no matter when someone joins an arena. Thanks!
