### ISSUE TITLE
NullPointerException on install/uninstall/update commands when update check is disabled.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#203]
Shouldn't the commands be disabled if the update check is off to avoid issues? Or output that the update check is disabled?

```
update:
  mode: off
  type: beta
  modules: false
```

```
[13:36:25] [Server thread/INFO]: player issued server command: /pa install mods
[13:36:25] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.2.119
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-756]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-756]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at net.slipcor.pvparena.commands.PAA_Install.commit(PAA_Install.java:73) ~[?:?]
    at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:263) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-756]
    ... 15 more
```

```
[13:43:37] [Server thread/INFO]: player issued server command: /pa install walls
[13:43:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.2.119
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-756]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-756]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at net.slipcor.pvparena.commands.PAA_Install.commit(PAA_Install.java:73) ~[?:?]
    at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:263) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-756]
    ... 15 more
```

```
[13:37:19] [Server thread/INFO]: player issued server command: /pa uninstall
[13:37:19] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.2.119
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-756]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-756]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at net.slipcor.pvparena.commands.PAA_Uninstall.listVersions(PAA_Uninstall.java:96) ~[?:?]
    at net.slipcor.pvparena.commands.PAA_Uninstall.commit(PAA_Uninstall.java:58) ~[?:?]
    at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:263) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-756]
    ... 15 more
```

When typing `/pa uninstall walls`, no error occurs. But it outputs to the client `[PVP Arena] Error while uninstalling: Walls`

When typing `/pa uninstall pa_m_walls`, no error occurs. Nothing outputs at all and nothing is uninstalled/deleted.

Typing `/pa update` outputs error while uninstalling: RespawnRelay as well as error in console.
![link](http://i.imgur.com/OqXjutA.png)

```
[13:48:12] [Server thread/INFO]: player issued server command: /pa update
[13:48:12] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.2.119
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-756]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-756]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-756]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-756]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at net.slipcor.pvparena.commands.PAA_Install.commit(PAA_Install.java:73) ~[?:?]
    at net.slipcor.pvparena.commands.PAA_Update.commit(PAA_Update.java:52) ~[?:?]
    at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:263) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-756]
    ... 15 more
```

**Comment by mibby** [comment]
Even with the update check enabled, there are some problems.

```
update:
  mode: true
  type: alpha
  modules: both
```

```/pa uninstall worldedit``` outputs ```Error while uninstalling: WorldEdit``` to the client. No errors in console. Same when trying the update command with the worldedit module in /files directory. Error while uninstalling, install fine.

When typing ```/pa install``` to get a list of modules/goals and versions to update, 'alpha' type is not up to date with the latest dev versions. For example, betterfight - v1.3.2119 is showing outdated with the correct version being (v1.3.2.94).

**Comment by mibby** [comment]
Per discussion;

Replace update/install system. Have ```/pa install``` and ```/pa update``` automatically pull updated/new mods/goals into the /files directory. Then on next server start-up, move those files into the corresponding /goals and /mods folders to 'update' the old files. As well as do so before it tries to initialize the modules already installed.

**Comment by mibby** [comment]
@slipcor Still errors without install.yml. See comment here. https://github.com/slipcor/pvparena/commit/40de720c25ae80622fc66a9685e003083108b89b#commitcomment-17723294

**Comment by slipcor** [comment]
@mibby the line numbers have changed, please update the pastebins

**Comment by mibby** [comment]
Re-typed the command to get the error. 
http://paste.ubuntu.com/17354300/

**Comment by slipcor** [comment]
@mibby Check the latest jenkins, I changed the updater and it should be not erroring because the command is disabled if you don't have the file OR you disabled the update check :)

**Comment by mibby** [comment]
Confirmed working as intended. No more errors as the install/uninstall/update commands are disabled. I assume if the update.modules setting is set to true, it automatically generates a new install.yml so it isn't missing. 

However, these problems are still present.

```/pa uninstall Walls``` can't uninstall the walls module. Client outputs 'Error while uninstalling: Walls' and the console just states;

```
[02:16:41] [Server thread/INFO]: player issued server command: /pa uninstall Walls
[02:16:41] [Server thread/ERROR]: [PVP Arena] could not delete file: pa_m_walls.jar
```

Also typing ```/pa uninstall``` on a non-OP/PA duty player outputs ```No permission to use the togglemod command!```. Shouldn't it state uninstall command? Install command states no permission for install command. 

When typing /pa update as a non-OP/PA duty player, it spams the person with no permission for 'togglemod' and 'install' command for every single module it tries to update. Would be better to check if they have permission to update first before running it against every single module that exists, so there would only be one output?

**Comment by slipcor** [comment]
1) if the uninstalling fails (can happen, as the Module Loader has no "unload" function) it will now try to do this on restart (and tell you)
2) uninstall prompt for missing perms fixed
3) update perm check before spamming, and if uninstall/install perm is missing, spam only once and then quit :)

**Comment by mibby** [comment]
Is it not uninstalling because the module is in use by an arena config?

In any case, all's good now. Great job. :) Scheduled uninstall works on restarts, uninstall has a language prompt, and update doesn't spam when you are missing permission to run an update check.

Though perhaps you should make it so ```/pa update``` doesn't uninstall modules if it can't find new ones to install located in the /files directory? Because if you type the update command when there is no new file to install / update to, it deletes all modules on restart. ```/pa update``` and ```/pa install``` does not automatically download / pull the latest file. You have to (currently) manually put them in the /files directory.

I'd also suggest making it so when typing update, if it can't unload the module to install the new one, schedule the install on start-up so it doesn't attempt to install, fail, then schedule an uninstall on restart (since it can't unload / uninstall the module while the server is live). 

Another possible suggestion. Have ```/pa update``` list what modules and goals are outdated / have an update rather than attempting to install/remove all modules existing with the command by default. That way you can specify a specific module/goal with ```/pa update <name>``` and add a ```/pa update all``` flag to update all modules outdated rather than uninstalling everything, even if it isn't outdated. As it doesn't really make sense to uninstall all modules. Perhaps a version check if the module is outdated?

And one final thing. Uninstalling goes by the traditional ```pa_m_module.jar``` name. It doesn't cover the dev build names. i.e. ```m_announcements-1.3.3-SNAPSHOT.jar```

```
[19:51:17] [Server thread/WARN]: [PVP Arena] file does not exist: pa_m_announcements.jar
[19:51:17] [Server thread/WARN]: [PVP Arena] file does not exist: pa_m_betterclasses.jar
[19:51:17] [Server thread/WARN]: [PVP Arena] file does not exist: pa_m_chestfiller.jar
[19:51:17] [Server thread/WARN]: [PVP Arena] file does not exist: pa_m_colorteams.jar
[19:51:17] [Server thread/WARN]: [PVP Arena] file does not exist: pa_m_vault.jar
[19:51:17] [Server thread/WARN]: [PVP Arena] file does not exist: pa_m_duel.jar
```

**Comment by slipcor** [comment]
okaaaaay

**Comment by slipcor** [comment]
2 things:

1) the update information does not work if you have the update disabled and the install yml is certainly outdated ;)

2) accounting for versions does not work, because the build names do not follow "pa_X" convention and.... I dunno. let's force people to use the proper downloads in the module pages that are properly renamed there :)  Dev builds always have a files.zip with proper naming ;)

and somewhere on jenkins has to be a proper named artifact, too. :)

3) The module update file is not much bigger than a check download would be xD if it was kilobytes even, sure, but we are talking 30 lines :)
