### ISSUE TITLE
Classes with dyed leather armor receive double armor, throw exceptions when loaded

### ISSUE THREAD

**Issue by tmad40blue** [slipcor/pvparena#208]
I've got an arena named Parkour that has several classes with dyed leather armor. When I attempt to load one of these classes, using `/pa parkour class load Normal` for example, I receive a duplicate of the armor in the hotbar and the following exception is printed in console:

```
[11:51:39 ERROR]: Could not pass event PAPlayerClassChangeEvent to pvparena v1.3.2.119
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.slipcor.pvparena.arena.ArenaPlayer.setArenaClass(ArenaPlayer.java:762) [pvparena.jar:?]
        at net.slipcor.pvparena.arena.Arena.selectClass(Arena.java:1406) [pvparena.jar:?]
        at net.slipcor.pvparena.commands.PAA_Class.commit(PAA_Class.java:105) [pvparena.jar:?]
        at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:380) [pvparena.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at net.slipcor.pvparena.modules.vaultsupport.VaultSupport.onClassChange(VaultSupport.java:664) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor715.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        ... 23 more
```

This is allowing players to be able to put on a second set of armor if their first set wears out or is taken away for one reason or another.

**Comment by slipcor** [comment]
@tmad40blue I need your exact module version, the Exception you have points to an empty line in the current version of Vault :)

**Comment by slipcor** [comment]
This points to the fact that you are not properly part of an arena. I fixed the symptom but still ... something is messed up :/

v1.3.2.129 - [Vault,Points,TempPerms] address github issue #208, fix issues related to this bug

**Comment by CCCCarsten** [comment]
Seems to be a similar problem like I have described in Spigot conversation. ;))

**Comment by slipcor** [comment]
@tmad40blue plz test on any version later than #129 :)
