### ISSUE TITLE
PlayerDeathEvent EventException

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#209]
Caused by this commit, arena runnable countdown not functioning properly anymore?
https://github.com/slipcor/pvparena/commit/b8e57400dbd4666f6f0bb97ea9a78f21dac524b8

Tested in KOTH. On player death, players are brought to a relay spawn point. Except they are stuck there permanently instead of only for 5 seconds. Had all players leave the arena, the arena did not end. Still on-going with no one remaining.

```
[15:14:52] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to pvparena v1.3.2.128
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.4.jar:git-Paper-763]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.4.jar:git-Paper-763]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-763]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-763]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-763]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:409) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.EntityPlayer.die(EntityPlayer.java:419) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:923) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.EntityHuman.damageEntity(EntityHuman.java:786) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.EntityPlayer.damageEntity(EntityPlayer.java:510) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:1022) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1169) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1614) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:48) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:5) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-763]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-763]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-763]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.loadables.ArenaModuleManager.parseStartCountDown(ArenaModuleManager.java:227) ~[?:?]
	at net.slipcor.pvparena.runnables.ArenaRunnable.<init>(ArenaRunnable.java:73) ~[?:?]
	at net.slipcor.pvparena.modules.respawnrelay.RelayRunnable.<init>(RelayRunnable.java:27) ~[?:?]
	at net.slipcor.pvparena.modules.respawnrelay.RespawnRelay.tryDeathOverride(RespawnRelay.java:149) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handleRespawn(PACheck.java:596) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handlePlayerDeath(PACheck.java:557) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerDeath(PlayerListener.java:327) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor291.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-763]
	... 23 more
```

**Comment by mibby** [comment]
Confirmed fixed in commit https://github.com/slipcor/pvparena/commit/7fe6aac62714f8abd0bd21444500eb3be62d6aad
