### ISSUE TITLE
IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#210]
This bug came back. 
```
[15:45:18] [Server thread/INFO]: [PVP Arena] Disabling pvparena v1.3.2.128
[15:45:18] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:407)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.remove(ScoreBoards.java:252)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.resetPlayer(ScoreBoards.java:303)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.loadables.ArenaModuleManager.resetPlayer(ArenaModuleManager.java:271)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1285)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1131)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1223)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:362)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:397)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.disablePlugins(CraftServer.java:337)
[15:45:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.stop(MinecraftServer.java:458)
[15:45:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:658)
[15:45:18] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:45:18] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:407)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.remove(ScoreBoards.java:252)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.resetPlayer(ScoreBoards.java:303)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.loadables.ArenaModuleManager.resetPlayer(ArenaModuleManager.java:271)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1285)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1131)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1223)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:362)
[15:45:18] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:397)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[15:45:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.disablePlugins(CraftServer.java:337)
[15:45:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.stop(MinecraftServer.java:458)
[15:45:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:658)
[15:45:18] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:45:18] [Server thread/INFO]: [PVP Arena] Plugin tracking disabled. See you soon?
[15:45:18] [Server thread/INFO]: [PVP Arena] disabled (version pvparena v1.3.2.128)
```

**Comment by slipcor** [comment]
v1.3.2.129 - [ScoreBoards] address github issue #210, IllegalPluginAccessException

**Comment by mibby** [comment]
Can't seem to replicate, assuming fixed. :)
