### ISSUE TITLE
NullPointerException scoreboard

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#228]
Reloaded an arena while players were still part of it. 

```
[21:53:38] [Server thread/WARN]: [PVP Arena] Task #151236 for pvparena v1.3.3.164 generated an exception
java.lang.NullPointerException
	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards$5RunLater.run(ScoreBoards.java:401) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-814]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.10.2.jar:git-Paper-814]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:786) [patched_1.10.2.jar:git-Paper-814]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.2.jar:git-Paper-814]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.2.jar:git-Paper-814]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.2.jar:git-Paper-814]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by slipcor** [comment]
That's a strange error you have there. Please try with v1.3.3.165 - oh yes I found your error line on the latest version and fixed the NPE!

**Comment by mibby** [comment]
I believe you fixed it. Can't reproduce when disabling the arena while players are in the battlefield now. So closing for now, assuming it is fixed.
