### ISSUE TITLE
IllegalStateException: Unregistered scoreboard component

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#229]
Shutdown server while players were in an arena.

```
[05:23:20] [Server thread/INFO]: [PVP Arena] Disabling pvparena v1.3.3.168
[05:23:20] [Server thread/WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[05:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:143)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards$3RunLater.run(ScoreBoards.java:309)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.remove(ScoreBoards.java:318)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.resetPlayer(ScoreBoards.java:360)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.loadables.ArenaModuleManager.resetPlayer(ArenaModuleManager.java:274)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1296)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1142)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1234)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:360)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:400)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:337)
[05:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:453)
[05:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:660)
[05:23:20] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:23:20] [Server thread/WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[05:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:143)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards$3RunLater.run(ScoreBoards.java:309)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.remove(ScoreBoards.java:318)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.scoreboards.ScoreBoards.resetPlayer(ScoreBoards.java:360)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.loadables.ArenaModuleManager.resetPlayer(ArenaModuleManager.java:274)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1296)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1142)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1234)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:360)
[05:23:20] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:400)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[05:23:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:337)
[05:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:453)
[05:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:660)
[05:23:20] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by slipcor** [comment]
check latest scoreboard module, I added a catch :)

**Comment by mibby** [comment]
Hard to confirm if fixed, but couldn't reproduce on shutdown while in an arena. So closing for now, assuming fixed. :)
