### ISSUE TITLE
BetterFight explosion occurs after players are kicked out of the arena on last life.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#236]
Received a complaint from someone that their item frames blew up after playing in an arena. It seems to be due to BetterFight module, the explodeondeath occurs after being teleported out of the arena on last life rather than prior to being kicked out.

Shouldn't the death explosion occur before being removed from the arena for having no lives remaining (and no spectate lounge)?

**Comment by slipcor** [comment]
I will look into it :)

**Comment by slipcor** [comment]
I am very sure that I had my reasons for doing that, but I did it instantly now:

v1.3.3.186 - [BetterFight] - create the explosion instantly. What could possibly go wrong?

**Comment by mibby** [comment]
@slipcor Apparently the change kills you twice per death now.

```
[05:59:46] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to pvparena v1.3.3.197
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-838]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-838]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-838]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-838]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-838]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:409) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.EntityPlayer.die(EntityPlayer.java:424) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:931) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:792) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:515) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1029) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1178) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1616) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:48) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:5) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-838]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-838]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-838]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.modules.betterclasses.BetterClasses.parseClassChange(BetterClasses.java:481) ~[?:?]
	at net.slipcor.pvparena.loadables.ArenaModuleManager.parseClassChange(ArenaModuleManager.java:221) ~[?:?]
	at net.slipcor.pvparena.arena.ArenaPlayer.setArenaClass(ArenaPlayer.java:755) ~[?:?]
	at net.slipcor.pvparena.goals.GoalInfect.commitPlayerDeath(GoalInfect.java:482) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handlePlayerDeath(PACheck.java:591) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerDeath(PlayerListener.java:351) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor263.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-838]
	... 23 more
```

**Comment by slipcor** [comment]
@mibby are you on latest BetterClasses? :O the issue is in the BetterClasses module

**Comment by slipcor** [comment]
v1.3.3.197 - [BetterClasses] - address github issue #236 - catch NPE

For some reason some entry can apparently be null :(

**Comment by mibby** [comment]
Confirmed fixed (as far as my quick testing goes) with resetdelay set to 3.
