### ISSUE TITLE
Cannot add Locations of differing worlds when /pa leave

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#241]
pa version: 1.3.3.194
spigot 1.10.2

```
[16:06:23] [Server thread/INFO]: bibo7 issued server command: /pa leave
[16:06:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.3.194
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
	at org.bukkit.Location.add(Location.java:311) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.slipcor.pvparena.arena.Arena$2RunLater.run(Arena.java:1503) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1526) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.removePlayer(Arena.java:1136) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.playerLeave(Arena.java:952) ~[?:?]
	at net.slipcor.pvparena.commands.PAG_Leave.commit(PAG_Leave.java:54) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:383) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	... 15 more
```

**Comment by Oruss7** [comment]
I thinks bibo7 have destroy 3 blocks on my spawn without OP and any permissions Oo

**Comment by slipcor** [comment]
https://ci2.craftyn.com/job/PVP%20Arena/

**Comment by Oruss7** [comment]
Really quick. Thanks !
