### ISSUE TITLE
IllegalStateException: Unregistered scoreboard component

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#256]
PVPArena dev 212
PaperSpigot dev 960 (MC 1.11)

Noticed this exception when the server restarted. Occurred when the server was in the process of shutting down. Assuming players may have been in an arena during this time since it was registering scoreboard components. 

```
[20:00:00] [Server thread/INFO]: [PVP Arena] Disabling pvparena v1.3.3.212
[20:00:00] [Server thread/WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:143)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena$1RunLater.run(Arena.java:1296)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetScoreboard(Arena.java:1305)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1454)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1215)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1391)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:360)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:400)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:346)
[20:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:477)
[20:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:684)
[20:00:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:00:00] [Server thread/WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:143)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena$1RunLater.run(Arena.java:1296)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetScoreboard(Arena.java:1305)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1454)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1215)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1391)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:360)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:400)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:346)
[20:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:477)
[20:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:684)
[20:00:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:00:00] [Server thread/WARN]: java.lang.IllegalStateException: Unregistered scoreboard component
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:143)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena$1RunLater.run(Arena.java:1296)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetScoreboard(Arena.java:1305)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1454)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.resetPlayers(Arena.java:1215)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1391)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.reset(ArenaManager.java:360)
[20:00:00] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onDisable(PVPArena.java:400)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[20:00:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:346)
[20:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:477)
[20:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:684)
[20:00:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:00:00] [Server thread/INFO]: [PVP Arena] Plugin tracking disabled. See you soon?
[20:00:00] [Server thread/INFO]: [PVP Arena] disabled (version pvparena v1.3.3.212)
```

**Comment by slipcor** [comment]
yeah should be an easy fix, I will be out for shopping now though :)

**Comment by mibby** [comment]
Haven't noticed this error recently on restarts, so assuming the commit above fixed the problem. Closing ticket.
