### ISSUE TITLE
Cant load class gear, saving works

### ISSUE THREAD

**Issue by Dragonisser** [slipcor/pvparena#259]
Tried to load a existing class gear but getting an error(same for vanilla ones). Saving works perfectly fine tho.

`[18:18:29 INFO]: Dragonisser issued server command: /pa TDM class load Witch
[18:18:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.3.209
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at net.slipcor.pvparena.loadables.ArenaModuleManager.parseClassChange(ArenaModuleManager.java:220) ~[?:?]
        at net.slipcor.pvparena.arena.ArenaPlayer.setArenaClass(ArenaPlayer.java:756) ~[?:?]
        at net.slipcor.pvparena.arena.Arena.selectClass(Arena.java:1657) ~[?:?]
        at net.slipcor.pvparena.commands.PAA_Class.commit(PAA_Class.java:111) ~[?:?]
        at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:383) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-850da7e-b5fb9a1]
        ... 15 more
`

**Comment by slipcor** [comment]
Yeah I fixed this in this commit:

v1.3.3.212 - fix issue #252 by catching a NPE

So please grab a version above 211 :)
