### ISSUE TITLE
Invalid Potion data output when loading custom potion from class chest.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#264]
PVPArena dev 222

Console outputs

```
[WARN]: [PVP Arena] Invalid Potion data - please update your Potion definitions!
```

when trying to load a class from a class chest that has a custom potion. Either with its name, lore, or NBT contents changed. Since the class contents are loaded from a chest, the potion should always work. Making the console output a bit redundant and spammy every time the class is loaded.

Shouldn't the potion definition check take into consideration classes loaded from a chest for custom items?

NullPointException from debug build.
```
[18:47:40] [Server thread/WARN]: [PVP Arena] Invalid Potion data - please update your Potion definitions!
[18:47:40] [Server thread/WARN]: java.lang.NullPointerException
[18:47:40] [Server thread/WARN]: 	at net.slipcor.pvparena.core.StringParser.getStringFromItemStack(StringParser.java:598)
[18:47:40] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.ArenaClass.equip(ArenaClass.java:220)
[18:47:40] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.ArenaPlayer.givePlayerFightItems(ArenaPlayer.java:203)
[18:47:40] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.chooseClass(Arena.java:268)
[18:47:40] [Server thread/WARN]: 	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:531)
[18:47:40] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor263.execute(Unknown Source)
[18:47:40] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[18:47:40] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[18:47:40] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:47:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[18:47:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[18:47:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:233)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:907)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:47:40] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:47:40] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
[18:47:40] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
[18:47:40] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
``

**Comment by mibby** [comment]
Closing since the warning output was removed. Hopefully it does not cause any problems with having custom defined potions in a class chest.
