### ISSUE TITLE
NoSuchMethodError: org.bukkit.DyeColor.getData

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#268]
PVPArena dev 223

Using the Beacons goal. Seems to break the arena too. :P

```
[11:48:55] [Server thread/WARN]: [PVP Arena] Task #58302 for pvparena v1.3.3.223 generated an exception
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
	at net.slipcor.pvparena.goals.beacons.BeaconRunnable.takeBeacon(BeaconRunnable.java:108) ~[?:?]
	at net.slipcor.pvparena.goals.beacons.BeaconRunnable.run(BeaconRunnable.java:91) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1026]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[11:53:00] [Server thread/WARN]: [PVP Arena] Task #57514 for pvparena v1.3.3.223 generated an exception
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
	at net.slipcor.pvparena.goals.beacons.BeaconRunnable.takeBeacon(BeaconRunnable.java:108) ~[?:?]
	at net.slipcor.pvparena.goals.beacons.BeaconRunnable.run(BeaconRunnable.java:91) ~[?:?]
	at net.slipcor.pvparena.goals.beacons.GoalBeacons.updateBeacon(GoalBeacons.java:788) ~[?:?]
	at net.slipcor.pvparena.goals.beacons.BeaconUpdateRunnable.run(BeaconUpdateRunnable.java:23) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1026]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1026]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1026]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by slipcor** [comment]
why do they always have to break things? :(

**Comment by slipcor** [comment]
check the latest gamemode zip :) it contains all shiny new goals!

**Comment by mibby** [comment]
No more error, working as intended. 👍
