### ISSUE TITLE
EventException - Could not pass event PlayerInteractEvent to pvparena

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#286]
PVPArena v1.3.4.259
ChestFiller v1.3.3.199
(Downloaded the files.zip from here https://ci.craftyn.com/job/PVP%20Arena%20Modules/172/ so no idea why it isn't v1.3.4)

Arena config.
http://paste.ubuntu.com/24252594/

@slipcor ChestFiller module isn't working for me. It first didn't scan the region battlefield to locate chests to fill (joined the game multiple times to make sure the arena started and then ended fully), so I had to set the chest locations manually. Then even with the chest inventories locations set manually, it isn't loading chest contents from a specific chest location. Might be caused by the exception as it occurs when someone types the command to join the arena.

```
  chestfiller:
    chestlocation: world:-8737,63,2299
    clear: true
    cfitems: '1'
    cfmaxitems: 5
    cfminitems: 5
```

```
[02:27:15] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.259
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1075]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1075]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1075]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1075]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1075]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:916) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1075]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1075]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_121]
	at net.slipcor.pvparena.modules.chestfiller.ChestFiller.fill(ChestFiller.java:310) ~[?:?]
	at net.slipcor.pvparena.modules.chestfiller.ChestFiller.parseStart(ChestFiller.java:211) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handleStart(PACheck.java:813) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.start(Arena.java:1931) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.start(Arena.java:1885) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:624) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor292.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1075]
	... 18 more
```

**Comment by mibby** [comment]
Seems to be fixed now, thanks.
