### ISSUE TITLE
Could not pass event PlayerInteractEvent to pvparena

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#287]
PVPArena 1.3.4.259
PlayerFinder 1.3.4.251

@slipcor 
```
[16:38:05] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.259
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1078]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.BlockPressurePlateWeighted.e(BlockPressurePlateWeighted.java:32) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.Entity.checkBlockCollisions(Entity.java:986) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:570) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:551) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1078]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1078]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.modules.playerfinder.PlayerFinder.onPlayerFind(PlayerFinder.java:49) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor815.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1078]
	... 23 more
```

**Comment by slipcor** [comment]
v1.3.4.259 - [PlayerFinder] - catch a NPE about player hands not existing

**Comment by mibby** [comment]
Thanks. Seems to be working as intended now. :)
