### ISSUE TITLE
Could not pass event PlayerInteractEvent - EventException

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#303]
Someone accidentally removed the chest filler chest location - exception occurred when trying to join the arena after. Perhaps catch the exception and have a nicer output if the chest cannot be found?

```
[14:36:39] [Server thread/WARN]: [PVP Arena] unrecognized material: 
[14:36:39] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.280
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1104]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:917) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1104]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.modules.chestfiller.ChestFiller.fill(ChestFiller.java:320) ~[?:?]
	at net.slipcor.pvparena.modules.chestfiller.ChestFiller.parseStart(ChestFiller.java:211) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handleStart(PACheck.java:814) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.start(Arena.java:1936) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.start(Arena.java:1890) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:644) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor312.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1104]
	... 18 more
```

**Comment by slipcor** [comment]
This should not be caused by someone removing a chest, but I will catch this exception and just continue moving on without the item currently trying to be added (an item in a chest is null, apparently)

**Comment by mibby** [comment]
>  not be caused by someone removing a chest, 

Someone removing the chest accidentally with worldedit. So no break event, just immediately removed. :P
