### ISSUE TITLE
org.bukkit.command.CommandException

### ISSUE THREAD

**Issue by falget** [slipcor/pvparena#305]
Hi, one player send duel to another, after accept duel, second player has been teleported to the arena but the first did not. After that second player try to leave from arena and send a command "/pa leave" but he did not leave and in console i got error:
`[16:16:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.4.281
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0(22.0)
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:99) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.slipcor.pvparena.arena.PlayerState.unload(PlayerState.java:180) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1540) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.removePlayer(Arena.java:1197) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.playerLeave(Arena.java:1014) ~[?:?]
	at net.slipcor.pvparena.commands.PAG_Leave.commit(PAG_Leave.java:54) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:389) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	... 15 more`
**After that he leave from the game and i get another message in console:**
`[16:16:59] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to pvparena v1.3.4.281
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:395) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1095) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:321) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0(22.0)
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:99) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.slipcor.pvparena.arena.PlayerState.unload(PlayerState.java:180) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1540) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.removePlayer(Arena.java:1197) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.playerLeave(Arena.java:1014) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerQuit(PlayerListener.java:833) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor901.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	... 12 more`
**After that he again enter to server and in console get error:**
`[16:17:02] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to pvparena v1.3.4.281
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0(22.0)
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:99) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	at net.slipcor.pvparena.arena.PlayerState.unload(PlayerState.java:180) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1540) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.removePlayer(Arena.java:1197) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.playerLeave(Arena.java:1014) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:753) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor783.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-7228328-11323bf]
	... 14 more`
**Player lost all their items, fix it please.
Use last dev build PvPArena and last MC 1.12 Spigot.**

**Comment by slipcor** [comment]
The latest dev should fix this issue, thanks for the detailed error report, I could fix it!
