### ISSUE TITLE
Console spamming this error

### ISSUE THREAD

**Issue by Zughy** [slipcor/pvparena#323]
```
24.08 17:34:00 [Server] ERROR Could not pass event PlayerInteractEvent to pvparena v1.3.4.284
24.08 17:34:00 [Server] INFO org.bukkit.event.EventException: null
24.08 17:34:00 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPressurePlateWeighted.e(BlockPressurePlateWeighted.java:32) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:991) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:573) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1829) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1429) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2132) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.n(EntityHuman.java:349) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1960) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:146) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:330) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:141) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.e(AbstractListenerPlayIn_v1_12_R1.java:76) [denizen-1.0.2-SNAPSHOT%20(3).jar:?]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:202) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [server.jar:git-Paper-1191]
24.08 17:34:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
24.08 17:34:00 [Server] INFO Caused by: java.lang.NullPointerException
```

**Comment by slipcor** [comment]
I suggest you report it to the person you ahve the jar from, the error is not triggered by PVP Arena, there is no class file I could look for errors - maybe the error is in:

```net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.e(AbstractListenerPlayIn_v1_12_R1.java:76) [denizen-1.0.2-SNAPSHOT%20(3).jar:?]```

**Comment by mcmonkey4eva** [comment]
It's PVP Arena, Denizen is not the fault just for being in the source trace.
The error message is incomplete though.

**Comment by Oruss7** [comment]
`24.08 17:34:00 [Server] INFO Caused by: java.lang.NullPointerException` cut where it's interressing ! please add full error

**Comment by Zughy** [comment]
The console was too long, saying "24 more"

Still, this time it printed out more :D 

```
15.09 15:43:17 [Server] ERROR Could not pass event PlayerInteractEvent to pvparena v1.3.4.284
15.09 15:43:17 [Server] INFO org.bukkit.event.EventException: null
15.09 15:43:17 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.BlockRedstoneOre.stepOn(BlockRedstoneOre.java:37) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:892) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1829) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1429) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2132) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.n(EntityHuman.java:349) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1960) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:146) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:330) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:141) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.e(AbstractListenerPlayIn_v1_12_R1.java:76) [denizen-1.0.2-SNAPSHOT%20(4).jar:?]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:202) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
15.09 15:43:17 [Server] INFO Caused by: java.lang.NullPointerException
15.09 15:43:17 [Server] INFO at net.slipcor.pvparena.modules.eventactions.PAListener.playerInteract(PAListener.java:112) ~[?:?]
15.09 15:43:17 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[server.jar:git-Paper-1196]
15.09 15:43:17 [Server] INFO ... 24 more
```

**Comment by mcmonkey4eva** [comment]
```

15.09 15:43:17 [Server] INFO Caused by: java.lang.NullPointerException
15.09 15:43:17 [Server] INFO at net.slipcor.pvparena.modules.eventactions.PAListener.playerInteract(PAListener.java:112) ~[?:?]
```
the magic lines!

**Comment by Oruss7** [comment]
```[18:28:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.291
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:955) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:536) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1806) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1422) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2117) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.n(EntityHuman.java:348) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:145) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:304) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:139) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.e(AbstractListenerPlayIn_v1_12_R1.java:76) [denizen-1.0.2-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
[18:28:26] [Server thread/INFO]: CommandBlock at 268,73,235 issued server command: /sudo osalid_1400 pa tnt_run
[18:28:28] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.291
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:955) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:536) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1806) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1422) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2117) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.n(EntityHuman.java:348) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:145) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:304) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:139) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.e(AbstractListenerPlayIn_v1_12_R1.java:76) [denizen-1.0.2-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
[18:28:28] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.291
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:955) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:536) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1806) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1422) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2117) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.n(EntityHuman.java:348) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:145) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:304) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:139) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.e(AbstractListenerPlayIn_v1_12_R1.java:76) [denizen-1.0.2-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
```

**Comment by slipcor** [comment]
sorry for the late reply - github did not send me any notifications for some reason!!

@mcmonkey4eva 

v1.3.4.291 - [EventActions] - Prevent NPEs for physical triggers of InteractEvents

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/

**Comment by Oruss7** [comment]
[14:23:49] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.291
org.bukkit.event.EventException: null
...
Caused by: java.lang.NullPointerException
at net.slipcor.pvparena.modules.specialjoin.SpecialJoin.onSpecialJoin(SpecialJoin.java:110) ~[?:?]
at sun.reflect.GeneratedMethodAccessor327.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
... 26 more
[14:23:51] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.291
org.bukkit.event.EventException: null
...
Caused by: java.lang.NullPointerException
at net.slipcor.pvparena.modules.eventactions.PAListener.playerInteract(PAListener.java:112) ~[?:?]
at sun.reflect.GeneratedMethodAccessor331.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
... 26 more

**Comment by Oruss7** [comment]
seems @slipcor SpecialJoin.onSpecialJoin also affected

**Comment by mcmonkey4eva** [comment]
@Oruss7 that's the same error as before. Are you sure you correctly updated your PvPArena modules?

**Comment by Oruss7** [comment]
After this ^^

**Comment by Oruss7** [comment]
Hello @slipcor !

After update:

```
[15:19:01] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.3.4.291
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:955) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:536) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:582) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.modules.specialjoin.SpecialJoin.onSpecialJoin(SpecialJoin.java:110) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor273.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	... 22 more
```

**Comment by slipcor** [comment]
Sorry again - I begin to question github's messaging system. I get spammed with updates on other repos but not this one :(

Update pushed to the modules repo!

**Comment by Oruss7** [comment]
i will. thanks

**Comment by Oruss7** [comment]
Fixed. Thanks.
