### ISSUE TITLE
Scoreboard Display name

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#329]
Hello,

I got:
```
Caused by: java.lang.IllegalArgumentException: Display name '§aPVP Arena§r - §einfected-vampire' is longer than the limit of 32 characters
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:40) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
```
Because i have enable scoreboard. Can you pick `general.prefix:` for scoreboard name instead of arena file please ?

Thanks you.

**Comment by slipcor** [comment]
I did add a check whether the name is too long.

If so, we try the prefix, if that still does not fit, we revert back to the initial name and shorten it to 32 characters ^^

**Comment by Oruss7** [comment]
![pvparena](https://user-images.githubusercontent.com/4788317/34100797-ef68552e-e3e3-11e7-9df9-14063b2d5bea.JPG)

**Comment by Oruss7** [comment]
default scorboard title ??

**Comment by slipcor** [comment]
oh, right, I think I found my error. build number 296 should fix this ^^

**Comment by Oruss7** [comment]
Done. Thanks !
