### ISSUE TITLE
ClassCastException: [Lorg.bukkit.inventory.ItemStack; cannot be cast to java.lang.String [

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#346]
PVPArena 1.13 as of commit https://github.com/slipcor/pvparena/commit/43f8dce3d3b000db18fb5bbe6d51f61a0bc56a34

```
[18:36:05] [Server thread/WARN]: java.lang.ClassCastException: [Lorg.bukkit.inventory.ItemStack; cannot be cast to java.lang.String
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.core.Config.getString(Config.java:730)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.blockdissolve.BlockDissolve.configParse(BlockDissolve.java:28)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.loadables.ArenaModuleManager.configParse(ArenaModuleManager.java:123)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ConfigurationManager.configParse(ConfigurationManager.java:296)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.<init>(Arena.java:116)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.load_arenas(ArenaManager.java:299)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onEnable(PVPArena.java:497)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[18:36:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by slipcor** [comment]
this should be fixed in https://github.com/slipcor/pvparena/commit/4554a948f337b9abb0ab6304e24c033f463d4c8c

(config changed from itemstack to material, and the internal logic was updated for that change)

**Comment by mibby** [comment]
Closing ticket. Will re-open as a new ticket if I notice it still being a problem with 1.13.2 and newer PVPArena builds.
