### ISSUE TITLE
PlayerInteractEvent - EventException: null

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#348]
Paper dev 398 (Spigot 1.13.2)
PVPArena 1.13 - Compiled as of https://github.com/slipcor/pvparena/commit/43f8dce3d3b000db18fb5bbe6d51f61a0bc56a34

Trying to interact with the ready up block.

Arena.yml
https://paste.ubuntu.com/p/hZtc79RwHG/

```
[06:29:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.13.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-398]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-398]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-398]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-398]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:267) ~[patched_1.13.2.jar:git-Paper-398]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:109) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1246) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-398]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-398]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ClassCastException: [Lorg.bukkit.inventory.ItemStack; cannot be cast to java.lang.String
	at net.slipcor.pvparena.core.Config.getString(Config.java:730) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.getReadyBlock(Arena.java:489) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.checkAndCommitCancel(PlayerListener.java:75) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:478) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor334.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-398]
	... 18 more
```

**Comment by mibby** [comment]
Closing ticket. Will re-open as a new ticket if I notice it still being a problem with 1.13.2 and newer PVPArena builds.
