### ISSUE TITLE
CommandException: Unhandled exception executing command 'pa' in plugin pvparena 

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#349]
Paper dev 398 (Spigot 1.13.2)
PVPArena 1.13 - Compiled as of https://github.com/slipcor/pvparena/commit/43f8dce3d3b000db18fb5bbe6d51f61a0bc56a34

Trying to leave the lounge with ```/pa leave```.

Arena.yml
https://paste.ubuntu.com/p/hZtc79RwHG/

```
[06:30:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.13.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-398]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-398]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1757) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1561) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-398]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-398]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-398]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ClassCastException: [Lorg.bukkit.inventory.ItemStack; cannot be cast to java.lang.String
	at net.slipcor.pvparena.core.Config.getString(Config.java:730) ~[?:?]
	at net.slipcor.pvparena.arena.ArenaPlayer.reloadInventory(ArenaPlayer.java:293) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1544) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.removePlayer(Arena.java:1187) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.playerLeave(Arena.java:1004) ~[?:?]
	at net.slipcor.pvparena.commands.PAG_Leave.commit(PAG_Leave.java:54) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:389) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-398]
	... 15 more
```

**Comment by mibby** [comment]
@slipcor I love you. Please fix. :(

**Comment by slipcor** [comment]
@mibby this error is not possible in the latest version, please double check. line 293 in ArenaPlayer does not call .getString() any more

**Comment by mibby** [comment]
@slipcor It is occurring though when trying to leave the arena with a newly created arena configuration with PVPArena v1.13.3 (build you gave me). :(

**Comment by Oruss7** [comment]
same

**Comment by mibby** [comment]
RE: Saturday build you gave me in discord.

```
[04:41:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.13.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1761) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1565) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-429]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.core.Config.getItems(Config.java:762) ~[?:?]
	at net.slipcor.pvparena.arena.ArenaPlayer.reloadInventory(ArenaPlayer.java:295) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.resetPlayer(Arena.java:1542) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.removePlayer(Arena.java:1185) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.playerLeave(Arena.java:1002) ~[?:?]
	at net.slipcor.pvparena.commands.PAG_Leave.commit(PAG_Leave.java:54) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:389) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-429]
	... 15 more
```

**Comment by mibby** [comment]
@slipcor Bump. :(

**Comment by mibby** [comment]
Closing ticket. Should be fixed in private discord build -- need to push to upstream branch.
