### ISSUE TITLE
Could not pass event EntityPickupItemEvent to pvparena

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#352]
**Issue**: PickupItemEvent exception noticed in console when testing an arena.

```
[01:45:44] [Server thread/ERROR]: Could not pass event EntityPickupItemEvent to pvparena v1.13.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-501]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-501]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-501]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityInsentient.a(EntityInsentient.java:557) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:538) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityMonster.movementTick(EntityMonster.java:24) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityZombie.movementTick(EntityZombie.java:211) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2134) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:261) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityMonster.tick(EntityMonster.java:28) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.EntityZombie.tick(EntityZombie.java:185) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1549) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1516) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1323) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1099) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-501]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_13_R2.entity.CraftZombie cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_13_R2.entity.CraftZombie and org.bukkit.entity.Player are in unnamed module of loader 'app')
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerPickupItem(PlayerListener.java:798) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1075.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-501]
	... 20 more
```

**Comment by mibby** [comment]
Assuming fixed. Bit hard to test this one, but will re-open if I still notice the exception occurring.
