### ISSUE TITLE
[Bug] [Respawn Relay] - java.lang.NullPointerException

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#93]
pvparena version 1.3.0.550
RespawnRelay - v1.3.0.515
```
[09:19:08] [Server thread/WARN]: [PVP Arena] Arena is null for player mibby while respawning!
[09:19:08] [Server thread/WARN]: [PVP Arena] Task #467847 for pvparena v1.3.0.550 generated an exception
java.lang.NullPointerException
	at net.slipcor.pvparena.modules.respawnrelay.RelayRunnable.commit(RelayRunnable.java:52) ~[?:?]
	at net.slipcor.pvparena.runnables.ArenaRunnable.run(ArenaRunnable.java:134) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
```

**Comment by mibby** [comment]
Assuming fixed with this commit. https://github.com/slipcor/pvparena_modules/commit/0a4aa967067a2b7dcc3416a5a0e1d9c96c110bb9
