### ISSUE TITLE
[null pointer] block dissolve 

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#94]
Versions :

CraftBukkit version git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks (MC: 1.7.9) (Implementing API version 1.7.9-R0.3-SNAPSHOT)

pvp Arena version 1.3.0.548

block dissolve version 1.3.0.515

Erreur : 
_______________________________

[11:34:48] [Server thread/INFO]: [PVP Arena] Erreur:
[11:34:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.0.548
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) ~[craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:740) ~[craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:956) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:817) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
Caused by: java.lang.NullPointerException
at net.slipcor.pvparena.modules.blockdissolve.BlockDissolve.reset(BlockDissolve.java:47) ~[?:?]
at net.slipcor.pvparena.loadables.ArenaModuleManager.reset(ArenaModuleManager.java:241) ~[?:?]
at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1180) ~[?:?]
at net.slipcor.pvparena.arena.Arena.stop(Arena.java:1516) ~[?:?]
at net.slipcor.pvparena.commands.PAA_Stop.commit(PAA_Stop.java:40) ~[?:?]
at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:377) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.7.9-R0.3.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
... 13 more

**Comment by Oruss7** [comment]
No tested in 1.8 servers

**Comment by slipcor** [comment]
fix will be up as soon as my jenkins works :)

**Comment by slipcor** [comment]
https://ci2.craftyn.com/job/PVP%20Arena%20Modules/lastSuccessfulBuild/artifact/m_BlockDissolve/target/
