### ISSUE TITLE
[Error] - Unhandled exception executing command

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#95]
```
[13:27:31] [Server thread/INFO]: mibby issued server command: /pa -ac sniper
[13:27:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.0.550
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.commands.PAG_Arenaclass.commit(PAG_Arenaclass.java:91) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:377) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	... 14 more
```

Restarted the server, users are able to switch teams without the error occurring. Not sure if an exception catch needs to be added.

**Comment by mibby** [comment]
Another error related to -ac.

```
[10:21:51] [Server thread/ERROR]: Exception when mibby attempted to tab complete /pa -ac 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/pa -ac ' in plugin pvparena v1.3.0.550
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:144) ~[spigot.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:213) ~[spigot.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.tabCompleteCommand(CraftServer.java:1600) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.tabComplete(CraftServer.java:1584) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1090) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1890) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PacketPlayInTabComplete.a(SourceFile:46) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PacketPlayInTabComplete.a(SourceFile:10) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_40]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_40]
	at net.slipcor.pvparena.goals.GoalFlags.getMain(GoalFlags.java:107) ~[?:?]
	at net.slipcor.pvparena.managers.TabManager.addTreesMatchingValueInHandlerList(TabManager.java:201) ~[?:?]
	at net.slipcor.pvparena.managers.TabManager.getMatches(TabManager.java:102) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onTabComplete(PVPArena.java:388) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135) ~[spigot.jar:git-Spigot-529ff99-2acb9e4]
	... 16 more
[10:21:53] [Server thread/ERROR]: Exception when mibby attempted to tab complete /pa -ac 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/pa -ac ' in plugin pvparena v1.3.0.550
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:144) ~[spigot.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:213) ~[spigot.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.tabCompleteCommand(CraftServer.java:1600) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.tabComplete(CraftServer.java:1584) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1090) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1890) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PacketPlayInTabComplete.a(SourceFile:46) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PacketPlayInTabComplete.a(SourceFile:10) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-529ff99-2acb9e4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_40]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_40]
	at net.slipcor.pvparena.goals.GoalFlags.getMain(GoalFlags.java:107) ~[?:?]
	at net.slipcor.pvparena.managers.TabManager.addTreesMatchingValueInHandlerList(TabManager.java:201) ~[?:?]
	at net.slipcor.pvparena.managers.TabManager.getMatches(TabManager.java:102) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onTabComplete(PVPArena.java:388) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135) ~[spigot.jar:git-Spigot-529ff99-2acb9e4]
	... 16 more
```

**Comment by mibby** [comment]
```
[10:45:10] [Server thread/INFO]: mibby issued server command: /pa -ac scout
[10:45:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.0.550
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-ea179b3-6e0120a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.commands.PAG_Arenaclass.commit(PAG_Arenaclass.java:91) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:377) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-ea179b3-6e0120a]
	... 15 more
```

**Comment by mibby** [comment]
```
[14:11:53] [Server thread/INFO]: mibby issued server command: /pa duel
[14:11:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.3.0.550
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f928e7a-d432434]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f928e7a-d432434]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f928e7a-d432434]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-f928e7a-d432434]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at net.slipcor.pvparena.modules.duel.DuelManager.commitCommand(DuelManager.java:64) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handleCommand(PACheck.java:136) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:357) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f928e7a-d432434]
	... 15 more
```
